// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package types

type OrderCreateReq struct {
	UserID  int64 `json:"user_id"`
	GoodsID int64 `json:"goods_id"`
	Num     int64 `json:"num"`
}

type OrderCreateResp struct {
}
