// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1
// Source: stock.proto

package stock

import (
	"context"

	"dtm-zero/service/stock/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductReq  = pb.DeductReq
	DeductResp = pb.DeductResp

	Stock interface {
		// 扣减库存
		Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error)
		// 扣减库存回滚
		DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

// 扣减库存
func (m *defaultStock) Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error) {
	client := pb.NewStockClient(m.cli.Conn())
	return client.Deduct(ctx, in, opts...)
}

// 扣减库存回滚
func (m *defaultStock) DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error) {
	client := pb.NewStockClient(m.cli.Conn())
	return client.DeductRollback(ctx, in, opts...)
}
