// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1
// Source: stock.proto

package server

import (
	"context"

	"dtm-zero/service/stock/internal/logic/stock"
	"dtm-zero/service/stock/internal/svc"
	"dtm-zero/service/stock/pb"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

// 扣减库存
func (s *StockServer) Deduct(ctx context.Context, in *pb.DeductReq) (*pb.DeductResp, error) {
	l := stocklogic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

// 扣减库存回滚
func (s *StockServer) DeductRollback(ctx context.Context, in *pb.DeductReq) (*pb.DeductResp, error) {
	l := stocklogic.NewDeductRollbackLogic(ctx, s.svcCtx)
	return l.DeductRollback(in)
}
