// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1
// Source: order.proto

package order

import (
	"context"

	"dtm-zero/service/order/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq  = pb.CreateReq
	CreateResp = pb.CreateResp

	Order interface {
		// 创建订单
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		// 创建订单回滚
		CreateRollback(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 创建订单
func (m *defaultOrder) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 创建订单回滚
func (m *defaultOrder) CreateRollback(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CreateRollback(ctx, in, opts...)
}
