// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID       int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID   int64 `gorm:"column:user_id;not null" json:"user_id"`
	GoodsID  int64 `gorm:"column:goods_id;not null;comment:商品id" json:"goods_id"`              // 商品id
	Num      int32 `gorm:"column:num;not null;comment:下单数量" json:"num"`                        // 下单数量
	RowState int32 `gorm:"column:row_state;not null;comment:-1:下单回滚废弃 0:待支付" json:"row_state"` // -1:下单回滚废弃 0:待支付
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
