// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStock = "stock"

// Stock mapped from table <stock>
type Stock struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodsID int64 `gorm:"column:goods_id;not null;comment:商品id" json:"goods_id"` // 商品id
	Num     int32 `gorm:"column:num;not null;comment:库存数量" json:"num"`           // 库存数量
}

// TableName Stock's table name
func (*Stock) TableName() string {
	return TableNameStock
}
